import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Wrapper from "./Wrapper";
import { Toaster } from "react-hot-toast";
import ProductState from "./Context/ProductState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stock Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Wrapper>
        <body className={inter.className}>
          <ProductState>
            <Navbar />
            {children}
          </ProductState>
        </body>
        <Toaster />
      </Wrapper>
    </html>
  );
}
